### ISSUE TITLE
TypeError: Cannot set property 'findBlock' of undefined

### ISSUE THREAD

**Issue by TheTechPony** [Darthfett/mineflayer-blockfinder#12]
This is after I updated the script for mineflayer 2.0.0

C:\Program Files\nodejs\node_modules\mineflayer-blockfinder\index.js:246
        bot.findBlock = findBlock;
                      ^

TypeError: Cannot set property 'findBlock' of undefined
    at inject (C:\Program Files\nodejs\node_modules\mineflayer-blockfinder\index
.js:246:23)
    at Object.<anonymous> (C:\Program Files\nodejs\reddit.js:6:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

**Comment by TheTechPony** [comment]
fixed: Just had to move blockFinderPlugin(bot); further down in code
