### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by jvyden** [Darthfett/mineflayer-blockfinder#17]
Using the following code:
```
case '!findportal':
        try {
        bot.findBlock({
          point: bot.entity.postition,
          matching: 181,
          maxDistance: 256,
          count: 1,
        }, function(err, blocks) {
          if (err) {
            return console.log(err)
          }
          if (blocks.length) {
            pos = blocks[0].position
            bot.chat("I found a portal at " + pos + ". Going there now...")
            bot.navigate.to(pos)
            return;
        } else {
          bot.chat("Portal not found.")
          return;
        }
      });
    } catch(err) {
      console.log(err)
    }
      break
```
Gives me:
```
C: <jvyden420> !findportal
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: undefined != null
    at optionsWithDefaults (/home/jvyden/jvybotmc/node_modules/mineflayer-blockfinder/index.js:234:20)
    at Bot.findBlockSync (/home/jvyden/jvybotmc/node_modules/mineflayer-blockfinder/index.js:248:23)
    at Bot.<anonymous> (/home/jvyden/jvybotmc/main.js:66:13)
    at emitMany (events.js:147:13)
    at Bot.emit (events.js:224:7)
    at checkForChatPatterns (/home/jvyden/jvybotmc/node_modules/mineflayer/lib/plugins/chat.js:44:80)
    at Client.bot._client.on (/home/jvyden/jvybotmc/node_modules/mineflayer/lib/plugins/chat.js:56:5)
    at emitTwo (events.js:126:13)
    at Client.emit (events.js:214:7)
    at FullPacketParser.deserializer.on (/home/jvyden/jvybotmc/node_modules/minecraft-protocol/src/client.js:82:12)
```
What am I doing wrong?

**Comment by rom1504** [comment]
Hi,
If you read your stacktrace, it says that an assertion has failed on line 234 of index.js
That's here https://github.com/Darthfett/mineflayer-blockfinder/blob/master/index.js#L234
The assertion is checking whether point is == to null. It's saying that it's undefined, which is == to null.
So your problem is that options.point is undefined.

So `bot.entity.postition` is undefined.

I don't have the rest of your code so I can't debug further.

However I assume that the problem is most likely
1. you are defining bot.entity.position to undefined
or
2. you executed that command too early, before the bot even knows its position.

**Comment by jvyden** [comment]
Thanks for the response. This is executed when the bot is fully in the game and can receive chat commands, such as this one. I can get the position of the bot in another command, so I dont *think* i'm doing anything wrong.

**Comment by rom1504** [comment]
well do a `console.log('position', bot.entity.position)` just before the find block to check the value

**Comment by jvyden** [comment]
```
C: <jvyden420> !findportal
position Vec3 {
  x: 422.6847707570055,
  y: 4.0009999999999994,
  z: 13.468442167245753 }
```
And then the error. Interesting.

**Comment by rom1504** [comment]
can you show your whole code ?

**Comment by Darthfett** [comment]
@jvyden420 , are you sure the sample code is the same code that is being executed here?  The error message says it was in `findBlockSync`, but your code calls `findBlock`.

**Comment by jvyden** [comment]
https://pastebin.com/ZAdiWaNk
Heres my code.

@Darthfett: I think i was testing the difference between the two.
Here is the error again, just incase the error is different.

```
{ AssertionError [ERR_ASSERTION]: undefined != null
    at optionsWithDefaults (/home/jvyden/jvybotmc/node_modules/mineflayer-blockfinder/index.js:234:20)
    at Bot.findBlock (/home/jvyden/jvybotmc/node_modules/mineflayer-blockfinder/index.js:262:23)
    at Bot.<anonymous> (/home/jvyden/jvybotmc/main.js:68:13)
    at emitMany (events.js:147:13)
    at Bot.emit (events.js:224:7)
    at checkForChatPatterns (/home/jvyden/jvybotmc/node_modules/mineflayer/lib/plugins/chat.js:44:80)
    at Client.bot._client.on (/home/jvyden/jvybotmc/node_modules/mineflayer/lib/plugins/chat.js:56:5)
    at emitTwo (events.js:126:13)
    at Client.emit (events.js:214:7)
    at FullPacketParser.deserializer.on (/home/jvyden/jvybotmc/node_modules/minecraft-protocol/src/client.js:82:12)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: null,
  operator: '!=' }
```

**Comment by rom1504** [comment]
you are not installing the plugin right, see example at https://github.com/Darthfett/mineflayer-blockfinder#usage

**Comment by jvyden** [comment]
If im correct, all i had to do was change
`blockFinderPlugin(bot);` to `bot.loadPlugin(blockFinderPlugin);`?
If so, its still giving the same result.

**Comment by jvyden** [comment]
I got it to work after copying the code, but it freezes the bot when trying to find a portal block. The ID *is* 181, right?

**Comment by rom1504** [comment]
you should use minecraft-data to retrieve the right id for the right version
